image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - develop
    - production
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - production
  script:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
    - sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
    - sudo chmod +x /usr/bin/docker-compose
    - docker-compose up -d --build
  when: manual